### ISSUE TITLE
Code-Input doesn‘t work.

### ISSUE THREAD

**Issue by kille250** [noaione/klibrarian#4]
Hey, you forgot in your code-validation in index.vue the return statement. It isn‘t really possible right now, to input the code via the input form. I‘m on mobile right now, I can make later on a pull request :D

**Comment by noaione** [comment]
I don't think I put any input validation on index, do you mean the invite page?

**Comment by kille250** [comment]
I mean this part in the index.vue: 
`function tryToExtractInviteCode(inviteCode: string) {
  try {
    const url = new URL(inviteCode);

    const params = new URLSearchParams(url.search);

    return params.get("token");
  } catch {
    // check if valid UUID
    const uuidre = /\w{8}(?:-\w{4}){3}-\w{12}/g;

    if (uuidre.test(inviteCode)) {
      inviteCode;
    }
  }

  return;
} `

You don‘t return the inviteCode :D

**Comment by kille250** [comment]
Sorry for the bad formatting, Im on mobile right now :(

**Comment by noaione** [comment]
Should be fixed with https://github.com/noaione/klibrarian/releases/tag/v0.1.4

**Comment by kille250** [comment]
Thank you very much! And thank you for this tool, searched a long time for a solution :D
